# Generated by Django 4.1.3 on 2022-12-19 11:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, choices=[('danger', 'danger'), ('success', 'success'), ('info', 'info'), ('warning', 'warning')], default='info', max_length=255)),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pictures/profile_rr3sky.png', upload_to='profile_pictures')),
                ('bio', models.TextField(blank=True, max_length='101', null=True)),
                ('facebook_page', models.URLField(blank=True, default='http://www.facebook.com/', null=True)),
                ('instagram_page', models.URLField(blank=True, default='http://www.instagram.com/', null=True)),
                ('twitter_page', models.URLField(blank=True, default='http://www.twitter.com/', null=True)),
                ('personal_website', models.URLField(blank=True, default='  ', null=True)),
                ('whatsapp_link', models.URLField(blank=True, default='http://www.wa.me/', null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
    ]
